# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 0
    gaps_out = 0
    border_size = 0

    # Use master layout instead of dwindle
    layout = scrolling

}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

scrolling {
  column_width = 0.5
  # explicit_column_widths = 0.333, 0.5, 0.667, 1.0
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

cursor {
    warp_on_change_workspace = 0
}
